# Generated by Django 4.0.1 on 2022-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=250, verbose_name='Описания проекта')),
                ('image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылкa')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
