# Generated by Django 4.0.1 on 2022-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылкa')),
            ],
            options={
                'verbose_name': 'Награды',
                'verbose_name_plural': 'Награда',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=100, verbose_name='Имя Фамилия')),
                ('team_image', models.ImageField(upload_to='project/images/', verbose_name='Изображение')),
                ('team_description', models.CharField(max_length=50, verbose_name='HardSkills')),
                ('team_url_github', models.URLField(blank=True, verbose_name='Ссылкa github')),
                ('team_url_telegram', models.URLField(blank=True, verbose_name='Ссылкa telegram')),
                ('team_url_vk', models.URLField(blank=True, verbose_name='Ссылкa vk')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
