# Generated by Django 4.0.1 on 2022-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('full_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('course', models.CharField(max_length=1, verbose_name='Курс')),
                ('description', models.TextField(verbose_name='Навыки')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('url_vk', models.URLField(blank=True, verbose_name='Ссылкa vk')),
                ('gmail', models.CharField(max_length=100, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
